version: "3.9"
services:

  postgres:
    image: postgis/postgis
    restart: unless-stopped
    volumes:
      - "./psql_data:/var/lib/postgresql/data"
      - "./init-schema.sh:/docker-entrypoint-initdb.d/init-schema.sh"
    env_file:
      - .env
    ports:
      - "5432:5432"

  api:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

networks:
  default:
    name: lct
    driver: bridge
